# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore OBSMidi/ConsoleExecutable/ConsoleExecutable.csproj
    - name: Build
      run: dotnet build --no-restore OBSMidi/ConsoleExecutable/ConsoleExecutable.csproj -o build
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        path: 'build'
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.pdb'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ steps.date.outputs.date }}
        artifacts: "release.zip"
        prerelease: true
